name: open_astro
description: "A partner app for Open Astro"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  dio: ^5.7.0 # http client
  flutter_svg: ^2.0.16 # svg provider
  flutter_screenutil: ^5.9.3 #adaptive
  flutter_native_splash: ^2.4.4 # splash screen
  flutter_rating: ^2.0.2 #rating star
  get: ^4.6.6 # state management
  image_picker: ^1.1.2 #image picker
  intl: ^0.20.2 #time format
  pretty_dio_logger: ^1.4.0 #intercepter
  pinput: ^5.0.0 #otp 
  share_plus: ^10.0.0 # share plus
  skeletonizer: ^1.4.3
  shared_preferences: ^2.5.3 # local storage
  video_player: ^2.9.2 # video player

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
